apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asset-backend
  template:
    metadata:
      labels:
        app: asset-backend
    spec:
      containers:
        - name: backend
          image: asset_management_system-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-db:3306/asset_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
